wc(tsconfig): types for vitest/globals
test/o-embed_test.ts:12:31 - error TS2307: Cannot find module '@social-embed/wc' or its corresponding type declarations.

12 import { OEmbedElement } from "@social-embed/wc";
                                 ~~~~~~~~~~~~~~~~~~
test/o-embed_test.ts:14:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

14 describe("o-embed", () => {
   ~~~~~~~~
test/o-embed_test.ts:15:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

15   it("is defined", () => {
     ~~
test/o-embed_test.ts:20:3 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

20   it("empty", async () => {
     ~~
test/o-embed_test.ts:29:3 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

29   describe("youtube", () => {
     ~~~~~~~~
test/o-embed_test.ts:33:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

33     it("renders with default values and sets URL", async () => {
       ~~
test/o-embed_test.ts:50:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

50     it("renders with a width", async () => {
       ~~
test/o-embed_test.ts:70:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

70     it("renders with a width at 100%", async () => {
       ~~
test/o-embed_test.ts:90:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

90     it("renders with a height", async () => {
       ~~
test/o-embed_test.ts:111:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

111     it("renders with a height at 100%", async () => {
        ~~
test/o-embed_test.ts:132:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

132     it("renders with a height / width", async () => {
        ~~
test/o-embed_test.ts:151:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

151     it("handles a click", async () => {
        ~~
test/o-embed_test.ts:175:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

175     it("renders with a set frameborder", async () => {
        ~~
test/o-embed_test.ts:194:5 - error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

194     it("renders with a set allowfullscreen", async () => {

and 129 lines more
✓ 21 modules transformed.